<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">addMapStep</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpGbG93RWxlbWVudAlwYXJlbnRGbG93RWxlbSA9IChGbG93RWxlbWVudCkgSURhdGFV
dGlsLmdldCggcGlwZWxpbmVDdXJzb3IsICJwYXJlbnRGbG93RWxlbSIgKTsNClN0cmluZwlzcmNG
aWVsZE5hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgInNyY0ZpZWxk
TmFtZSIgKTsNClN0cmluZwlkZXN0RmllbGROYW1lID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlw
ZWxpbmVDdXJzb3IsICJkZXN0RmllbGROYW1lIiApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgp
Ow0KDQpGbG93TWFwQ29weSBmbWMgPSBuZXcgRmxvd01hcENvcHkobnVsbCk7DQpmbWMuc2V0TWFw
RnJvbSggc3JjRmllbGROYW1lLmNoYXJBdCgwKSA9PSAnLycgPyBzcmNGaWVsZE5hbWUgOiAiLyIr
c3JjRmllbGROYW1lKyI7MTswIik7DQppZiAoZm1jLmdldE1hcEZyb20oKS5zdGFydHNXaXRoKCIv
bnVsbCIpKSB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiV3hHZW5lcmF0ZTogbWFwIHNyYyAi
K3NyY0ZpZWxkTmFtZSsiIG5vdCBmb3VuZCIpOw0KZm1jLnNldE1hcFRvKCBkZXN0RmllbGROYW1l
LmNoYXJBdCgwKSA9PSAnLycgPyBkZXN0RmllbGROYW1lIDogIi8iK2Rlc3RGaWVsZE5hbWUrIjsx
OzAiKTsNCmlmIChmbWMuZ2V0TWFwVG8oKS5zdGFydHNXaXRoKCIvbnVsbCIpKSB0aHJvdyBuZXcg
U2VydmljZUV4Y2VwdGlvbigiV3hHZW5lcmF0ZTogbWFwIGRlc3QgIitkZXN0RmllbGROYW1lKyIg
bm90IGZvdW5kIik7DQoNCkZsb3dNYXAgZm0gPSBuZXcgRmxvd01hcChudWxsKTsNCmZtLmFkZE5v
ZGUoZm1jKTsNCnBhcmVudEZsb3dFbGVtLmFkZE5vZGUoZm0pOw0KDQpJRGF0YUN1cnNvciBwaXBl
bGluZUN1cnNvck91dCA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGFVdGlsLnB1dCggcGlw
ZWxpbmVDdXJzb3JPdXQsICJwYXJlbnRGbG93RWxlbSIsIHBhcmVudEZsb3dFbGVtICk7DQpwaXBl
bGluZUN1cnNvck91dC5kZXN0cm95KCk7DQoJ</value>
</Values>
