<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">addMap</value>
  <array name="sig" type="value" depth="1">
    <value>[i] object:0:required parentFlowElem</value>
    <value>[i] field:0:optional srcFieldName</value>
    <value>[i] field:0:required destFieldName</value>
    <value>[i] field:0:required destFieldValue</value>
    <value>[i] field:0:required mapSide {"inputMap","outputMap"}</value>
    <value>[o] object:0:required parentFlowElem</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKdHJ5IHsKCUZsb3dFbGVtZW50CXBhcmVudEZsb3dFbGVtID0gKEZsb3dFbGVtZW50KSBJ
RGF0YVV0aWwuZ2V0KCBwaXBlbGluZUN1cnNvciwgInBhcmVudEZsb3dFbGVtIiApOwoJU3RyaW5n
CXNyY0ZpZWxkTmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAic3Jj
RmllbGROYW1lIiApOwoJU3RyaW5nCWRlc3RGaWVsZE5hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5n
KCBwaXBlbGluZUN1cnNvciwgImRlc3RGaWVsZE5hbWUiICk7CglTdHJpbmcJZGVzdEZpZWxkVmFs
dWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImRlc3RGaWVsZFZhbHVl
IiApOwoJU3RyaW5nCW1hcFNpZGUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNv
ciwgIm1hcFNpZGUiICk7CgoJRmxvd01hcENvcHkgZm1jID0gbnVsbDsKCUZsb3dNYXBTZXQgZm1z
ID0gbnVsbDsKCWlmIChzcmNGaWVsZE5hbWUgPT0gbnVsbCAmJiBkZXN0RmllbGROYW1lICE9IG51
bGwgJiYgZGVzdEZpZWxkVmFsdWUgIT0gbnVsbCl7CgkJZm1zID0gbmV3IEZsb3dNYXBTZXQobnVs
bCk7CgkJZm1zLnNldE92ZXJ3cml0ZSh0cnVlKTsKCQlmbXMuc2V0VmFyaWFibGVzKGZhbHNlKTsK
CQlmbXMuc2V0RW5jb2RpbmcoRmxvd01hcFNldC5FTkNPRElOR19YTUxfVkFMVUVTKTsKCQlmbXMu
c2V0TmFtZSgiU2V0dGVyIik7CgkJZm1zLnNldEZpZWxkKCBkZXN0RmllbGROYW1lLmNoYXJBdCgw
KSA9PSAnLycgPyBkZXN0RmllbGROYW1lIDogIi8iK2Rlc3RGaWVsZE5hbWUrIjsxOzAiICk7CgkJ
Zm1zLnNldElucHV0KGRlc3RGaWVsZFZhbHVlKTsKCX0gZWxzZSB7CgkJZm1jID0gbmV3IEZsb3dN
YXBDb3B5KG51bGwpOwoJCWZtYy5zZXRNYXBGcm9tKCBzcmNGaWVsZE5hbWUuY2hhckF0KDApID09
ICcvJyA/IHNyY0ZpZWxkTmFtZSA6ICIvIitzcmNGaWVsZE5hbWUrIjsxOzAiKTsKCQlpZiAoZm1j
LmdldE1hcEZyb20oKS5zdGFydHNXaXRoKCIvbnVsbCIpKSB0aHJvdyBuZXcgU2VydmljZUV4Y2Vw
dGlvbigiV3hHZW5lcmF0ZTogbWFwIHNyYyAiK3NyY0ZpZWxkTmFtZSsiIG5vdCBmb3VuZCIpOwoJ
CWZtYy5zZXRNYXBUbyggZGVzdEZpZWxkTmFtZS5jaGFyQXQoMCkgPT0gJy8nID8gZGVzdEZpZWxk
TmFtZSA6ICIvIitkZXN0RmllbGROYW1lKyI7MTswIik7CgkJaWYgKGZtYy5nZXRNYXBUbygpLnN0
YXJ0c1dpdGgoIi9udWxsIikpIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJXeEdlbmVyYXRl
OiBtYXAgZGVzdCAiK2Rlc3RGaWVsZE5hbWUrIiBub3QgZm91bmQiKTsKCX0KCWlmIChtYXBTaWRl
LmVxdWFscygiaW5wdXRNYXAiKSkgewoJCWlmIChwYXJlbnRGbG93RWxlbS5nZXRJbnB1dE1hcCgp
ID09IG51bGwpewoJCQlwYXJlbnRGbG93RWxlbS5zZXRJbnB1dE1hcChuZXcgRmxvd01hcChudWxs
KSk7CgkJfQoJCXBhcmVudEZsb3dFbGVtLmdldElucHV0TWFwKCkuYWRkTm9kZSggZm1jICE9IG51
bGwgPyBmbWMgOiBmbXMgKTsKCX0gZWxzZSB7CgkJaWYgKHBhcmVudEZsb3dFbGVtLmdldE91dHB1
dE1hcCgpID09IG51bGwpewoJCQlwYXJlbnRGbG93RWxlbS5zZXRPdXRwdXRNYXAobmV3IEZsb3dN
YXAobnVsbCkpOwoJCX0KCQlwYXJlbnRGbG93RWxlbS5nZXRPdXRwdXRNYXAoKS5hZGROb2RlKCBm
bWMgIT0gbnVsbCA/IGZtYyA6IGZtcyApOwoJfQoKCUlEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vy
c29yLCAicGFyZW50Rmxvd0VsZW0iLCBwYXJlbnRGbG93RWxlbSApOwp9IGZpbmFsbHkgewoJcGlw
ZWxpbmVDdXJzb3IuZGVzdHJveSgpOwp9CgkK</value>
</Values>
